# Generated by Django 3.2.9 on 2022-06-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20211130_0929'),
        ('recipes', '0002_auto_20220523_1505'),
    ]

    operations = [
    ]
